INSERT INTO music (name, movie, artist, language, year) VALUES 
('Kirik Party', 'Kirik Party', 'V. Harikrishna', 'Kannada', 2016),
('Belageddu', 'Kirik Party', 'V. Harikrishna', 'Kannada', 2016),
('Karagida Baanalli', 'Pailwaan', 'Arjun Janya', 'Kannada', 2019),
('Mungaru Male', 'Mungaru Male', 'Arjun Janya', 'Kannada', 2006),
('Chaluvadiyo Ninna', 'Geetha', 'Anup Rubens', 'Kannada', 2019),
('Neene Modalu Neene Kone', 'Sarvajanikarige Suvarnavakaasha', 'Midhun Mukundan', 'Kannada', 2019),
('Love You Chinna', 'Roberrt', 'Arjun Janya', 'Kannada', 2021),
('Hodallella', 'Tagaru', 'Charan Raj', 'Kannada', 2018),
('Thamnam Thamnam', 'Pailwaan', 'Arjun Janya', 'Kannada', 2019),
('Yenammi Yenammi', 'Ayogya', 'Arjun Janya', 'Kannada', 2018),
('Open The Bottle', 'Raajakumara', 'V. Harikrishna', 'Kannada', 2017),
('Jothe Jotheyali', 'Geetha', 'Anup Rubens', 'Kannada', 2019),
('Yenagaga Madali', 'Bharaate', 'Arjun Janya', 'Kannada', 2019),
('Ondu Male Bille', 'Chakravyuha', 'S. Thaman', 'Kannada', 2016),
('Bekhayali', 'Kabir Singh', 'Sachet-Parampara', 'Kannada', 2019),
('Yaaro Geethe', 'Yajamana', 'V. Harikrishna', 'Kannada', 2019),
('Kanda Sambrama', 'Geetha', 'Anup Rubens', 'Kannada', 2019),
('Neene Neene', 'Akira', 'B. Ajaneesh Loknath', 'Kannada', 2016),
('Ninna Poojege Bande Mahadeshwara', 'Hombanna', 'Arjun Janya', 'Kannada', 2017),
('Helilla Yaarallu', 'Mugulu Nage', 'V. Harikrishna', 'Kannada', 2017),
('Kanada Bhavana', 'Ugramm', 'Ravi Basrur', 'Kannada', 2014),
('Vaasthu Prakaara', 'Vaasthu Prakaara', 'V. Harikrishna', 'Kannada', 2015),
('Yenendu Hesaridali', 'Rambo 2', 'Arjun Janya', 'Kannada', 2018),
('Ondu Motteya Kathe', 'Ondu Motteya Kathe', 'Midhun Mukundan', 'Kannada', 2017),
('Marete Hoyithe', 'Mungaru Male', 'Arjun Janya', 'Kannada', 2006),
('Jokae', 'Raajakumara', 'V. Harikrishna', 'Kannada', 2017),
('Gaali Vaaluga', 'Katheyonda Helide', 'Arjun Janya', 'Kannada', 2017),
('Kannada Naadina', 'Googly', 'Joshua Sridhar', 'Kannada', 2013),
('Bombe Helutaithe', 'Raajakumara', 'V. Harikrishna', 'Kannada', 2017),
('Nanna Preetiya', 'Mungaru Male', 'Arjun Janya', 'Kannada', 2006),
('Samshaya', 'Victory', 'Arjun Janya', 'Kannada', 2013),
('Saalutillave', 'Simple Agi Ondh Love Story', 'B. Ajaneesh Loknath', 'Kannada', 2013),
('Shivappa Kayo Tande', 'Bettada Hoovu', 'M. Ranga Rao', 'Kannada', 1985),
('Hosa Belaku', 'Hosa Belaku', 'M. Ranga Rao', 'Kannada', 1982),
('Jotheyalli', 'Geetha', 'Ilaiyaraaja', 'Kannada', 1981),
('Naguva Nayana', 'Pallavi Anu Pallavi', 'Ilaiyaraaja', 'Kannada', 1983),
('Chigurida Kanasu', 'Chigurida Kanasu', 'V. Manohar', 'Kannada', 2003),
('Minchagi Neenu Baralu', 'Gaalipata', 'V. Harikrishna', 'Kannada', 2008),
('Hrudaya Hadithu', 'Hrudaya Hadithu', 'Upendra Kumar', 'Kannada', 1989),
('Kanasalu Neene', 'Hombisilu', 'Rajan-Nagendra', 'Kannada', 1978),
('Aa Devara Haadu', 'Ganeshana Maduve', 'Hamsalekha', 'Kannada', 1990),
('Anisutide', 'Mungaru Male', 'Arjun Janya', 'Kannada', 2006),
('Eradu Kanasu', 'Eradu Kanasu', 'Rajan-Nagendra', 'Kannada', 1974),
('Cheluveya Ninna Nodalu', 'Cheluveye Ninne Nodalu', 'V. Harikrishna', 'Kannada', 2010),
('Kivi Maatu', 'Rangitaranga', 'Anup Bhandari', 'Kannada', 2015),
('Jotheyagi', 'Milana', 'Mano Murthy', 'Kannada', 2007),
('Sanju Weds Geetha', 'Sanju Weds Geetha', 'Jassie Gift', 'Kannada', 2011),
('Noorondu Nenapu', 'Noorondu Nenapu', 'Gurukiran', 'Kannada', 2017),
('Butta Bomma', 'Ala Vaikunthapurramuloo', 'Thaman S', 'Telugu', 2020),
('Samajavaragamana', 'Ala Vaikunthapurramuloo', 'Thaman S', 'Telugu', 2019),
('Mind Block', 'Sarileru Neekevvaru', 'Devi Sri Prasad', 'Telugu', 2020),
('Ramuloo Ramulaa', 'Ala Vaikunthapurramuloo', 'Thaman S', 'Telugu', 2020),
('Neeli Neeli Aakasam', '30 Rojullo Preminchadam Ela', 'Anup Rubens', 'Telugu', 2021),
('Psycho Saiyaan', 'Saaho', 'Tanishk Bagchi', 'Telugu', 2019),
('Vachinde', 'Fidaa', 'Shakthikanth Karthick', 'Telugu', 2017),
('Inkem Inkem Inkem Kaavaale', 'Geetha Govindam', 'Gopi Sundar', 'Telugu', 2018),
('Seeti Maar', 'DJ: Duvvada Jagannadham', 'Devi Sri Prasad', 'Telugu', 2017),
('Yenti Yenti', 'Geetha Govindam', 'Gopi Sundar', 'Telugu', 2018),
('Oo Antava', 'Pushpa', 'Devi Sri Prasad', 'Telugu', 2021),
('Sitharala Sirapadu', 'Ala Vaikunthapurramuloo', 'Thaman S', 'Telugu', 2020),
('Vachindamma', 'Geetha Govindam', 'Gopi Sundar', 'Telugu', 2018),
('Priyathama', 'Majili', 'Gopi Sundar', 'Telugu', 2019),
('Kaathuka Kannale', 'Dear Comrade', 'Justin Prabhakaran', 'Telugu', 2019),
('Ninnu Kori Varnam', 'Gharshana', 'Harris Jayaraj', 'Telugu', 2004),
('Nuvve Nuvve', 'Kick', 'Thaman S', 'Telugu', 2009),
('Kanule', 'Kanche', 'Chirantan Bhatt', 'Telugu', 2015),
('Elluvochi Godaramma', 'Gaddalakonda Ganesh', 'Mickey J Meyer', 'Telugu', 2019),
('Rangasthalam', 'Rangasthalam', 'Devi Sri Prasad', 'Telugu', 2018),
('Mellaga Mellaga', 'Gunde Jaari Gallanthayyinde', 'Anup Rubens', 'Telugu', 2013),
('Nee Kannu Neeli Samudram', 'Uppena', 'Devi Sri Prasad', 'Telugu', 2021),
('Nee Kallathoti', 'Tholi Prema', 'Deva', 'Telugu', 1998),
('Rowdy Baby', 'Maari 2', 'Yuvan Shankar Raja', 'Tamil', 2018),
('Why This Kolaveri Di', '3', 'Anirudh Ravichander', 'Tamil', 2012),
('Vaathi Coming', 'Master', 'Anirudh Ravichander', 'Tamil', 2021),
('Mukkala Mukabala', 'Kadhalan', 'A. R. Rahman', 'Tamil', 1994),
('Aalaporan Thamizhan', 'Mersal', 'A. R. Rahman', 'Tamil', 2017),
('Munbe Vaa', 'Sillunu Oru Kaadhal', 'A. R. Rahman', 'Tamil', 2006),
('Anbe En Anbe', 'Dharma Durai', 'Yuvan Shankar Raja', 'Tamil', 2016),
('Nenjukkul Peidhidum', 'Vaaranam Aayiram', 'Harris Jayaraj', 'Tamil', 2008),
('Kannamma', 'Kaala', 'Santhosh Narayanan', 'Tamil', 2018),
('Ennai Vittu', 'Deiva Thirumagal', 'G. V. Prakash Kumar', 'Tamil', 2011),
('Maari Thara Local', 'Maari', 'Anirudh Ravichander', 'Tamil', 2015),
('Vaseegara', 'Minnale', 'Harris Jayaraj', 'Tamil', 2001),
('Naan Un Azhaginile', 'Thirumanam Ennum Nikkah', 'Ghibran', 'Tamil', 2014),
('Un Vizhigalil', 'Maan Karate', 'Anirudh Ravichander', 'Tamil', 2014),
('Yathe Yathe', 'Aadukalam', 'G. V. Prakash Kumar', 'Tamil', 2011),
('Kadhal Rojave', 'Roja', 'A. R. Rahman', 'Tamil', 1992),
('Mental Manadhil', 'OK Kanmani', 'A. R. Rahman', 'Tamil', 2015),
('Pachchai Nirame', 'Alaipayuthey', 'A. R. Rahman', 'Tamil', 2000),
('Evano Oruvan', 'Alaipayuthey', 'A. R. Rahman', 'Tamil', 2000),
('Yethi Yethi', 'Vaaranam Aayiram', 'Harris Jayaraj', 'Tamil', 2008);
